services:
  auth-db:
    image: postgres:15
    platform: linux/arm64/v8
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  booking-db:
    image: postgres:15
    platform: linux/arm64/v8
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
    ports:
      - "5434:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data

  ai-db:
    image: postgres:15
    platform: linux/arm64/v8
    environment:
      POSTGRES_DB: ai_db
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    ports:
      - "5435:5432"
    volumes:
      - ai_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    platform: linux/arm64/v8
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10
    platform: linux/arm64/v8
    ports:
      - "4222:4222"
      - "8222:8222"

  auth-service:
    build: ./services/auth-service
    environment:
      PORT: 3001
      DATABASE_URL: postgres://auth_user:auth_password@auth-db:5432/auth_db
      REDIS_URL: redis://redis:6379
      NATS_URL: nats://nats:4222
      JWT_SECRET: supersecret
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    depends_on:
      - auth-db
      - redis
      - nats
    ports:
      - "3001:3001"

  booking-service:
    build: ./services/booking-service
    environment:
      PORT: 3002
      DATABASE_URL: postgres://booking_user:booking_password@booking-db:5432/booking_db
      REDIS_URL: redis://redis:6379
      NATS_URL: nats://nats:4222
      AI_SERVICE_URL: http://ai-service:3003
      JWT_SECRET: supersecret
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    depends_on:
      - booking-db
      - redis
      - nats
      - ai-service
    ports:
      - "3002:3002"

  ai-service:
    build: ./services/ai-service
    environment:
      PORT: 3003
      DATABASE_URL: postgres://ai_user:ai_password@ai-db:5432/ai_db
      NATS_URL: nats://nats:4222
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    depends_on:
      - ai-db
      - nats
    ports:
      - "3003:3003"

volumes:
  auth_db_data:
  booking_db_data:
  ai_db_data:


