services:
  - type: web
    name: auth-service
    env: node
    plan: free
    rootDir: services/auth-service
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: |
      npx prisma migrate deploy && node dist/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: auth-db
          property: connectionString

  - type: web
    name: booking-service
    env: node
    plan: free
    rootDir: services/booking-service
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: |
      npx prisma migrate deploy && node dist/index.js
    envVars:
      - key: PORT
        value: 3002
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: booking-db
          property: connectionString
      - key: REDIS_URL
        sync: false # Set this in the Render dashboard (e.g., Redis Labs/Upstash URL)
      - key: AI_SERVICE_URL
        sync: false # Set to the deployed ai-service URL after first deploy

  - type: web
    name: ai-service
    env: node
    plan: free
    rootDir: services/ai-service
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: |
      npx prisma migrate deploy && node dist/index.js
    envVars:
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        fromDatabase:
          name: ai-db
          property: connectionString

databases:
  - name: auth-db
    plan: free
    databaseName: auth_db
  - name: booking-db
    plan: free
    databaseName: booking_db
  - name: ai-db
    plan: free
    databaseName: ai_db
